---
- hosts: [rhel]
  remote_user: root
  
  vars:
    account: cdk

  tasks:
    - name: Delete old testing account
      user: name={{ account }} state=absent remove=yes
 
    - name: Create new testing account
      user: name={{ account }} state=present group=wheel generate_ssh_key=yes comment="CDK qe testing account"

    - name: Set authorized keys for testing account
      authorized_key: user={{ account }} key="{{ lookup('file', 'id_rsa.pub') }}"

